Move CustomMessageSetting.available_messages to MessageCustomize::Locale
ishikawa999/redmine_message_customize pull request #20
Opened 2019-07-12 03:05 UTC by ishikawa999

#19 

flatten_hashメソッドを使っている以外はI18n絡みの処理で、CustomMessageSettingの情報を使うわけでもないためMessageCustomize::Localeにメソッドを移動します。

また、available_messagesメソッドは保存時(バリデーション)、画面の表示(options)のときに毎回呼び出されるため、@available_messagesに入れておくように変更しました。

確認をお願いいたします。

2019-07-13 05:18 UTC, yui-har requested changes

2019-07-13 05:18 UTC, yui-har commented on lib/message_customize/locale.rb
> +        if @available_messages[lang].present?
MessageCustomize::Locale.reload! を実施しているので、 @available_messages[lang] からメッセージを取得すればよいと思います。
suggestion機能で複数行の一括指定が分からなかったので、パッチを貼り付けます。
<pre>
diff --git a/lib/message_customize/locale.rb b/lib/message_customize/locale.rb
index d060609..3f5e0e9 100644
--- a/lib/message_customize/locale.rb
+++ b/lib/message_customize/locale.rb
@@ -26,17 +26,8 @@ module MessageCustomize

       def available_messages(lang)
         lang = :"#{lang}"
-        if @available_messages[lang].present?
-          @available_messages[lang]
-        else
-          messages = I18n.backend.send(:translations)[lang]
-          if messages.nil?
-            MessageCustomize::Locale.reload!(lang)
-            messages = I18n.backend.send(:translations)[lang] || {}
-          end
-          @available_messages[lang] = messages
-          messages
-        end
+        self.reload!(lang) if @available_messages[lang].blank?
+        @available_messages[lang] || {}
       end
     end
   end
</pre>

2019-07-16 03:00 UTC, ishikawa999 commented on lib/message_customize/locale.rb
> +        if @available_messages[lang].present?
@yui-har 
ご確認いただきありがとうございました。
ご指摘いただいた点について、修正を加えました。 https://github.com/ishikawa999/redmine_message_customize/pull/20/commits/b090792b6fd4fab9b6b008bdca5599942f978f22

他に気になる点はございませんか？

2019-07-16 03:07 UTC, yui-har commented on lib/message_customize/locale.rb
> +        if @available_messages[lang].present?
> 他に気になる点はございませんか？

他に気になる点はございません。OKと思います。

2019-07-16 03:09 UTC, yui-har approved these changes

2019-07-16 04:21 UTC, merged